# Changes here will be overwritten by Copier
_commit: 0.1.0-7-ga5b05ea
_src_path: /p/dev/copier-mk-pdm
author_email: fritz@mahnke.tech
author_fullname: Fritz Mahnke
copyright_date: '2025'
copyright_holder: Fritz Mahnke
copyright_holder_email: fritz@mahnke.tech
copyright_license: GNU General Public License v3.0
docker_registry: registry.mahnke.tech
docker_registry_path: application
project_description: mktech standard library
project_name: mktech-mktech
python_package_command_line_name: ''
python_package_distribution_name: mktech
python_package_import_name: mktech
repository_name: mktech
repository_namespace: fmahnke
repository_provider: github.com

