[project]
name = "mktech"
version = "0.5.0"
requires-python = ">=3.10"

dependencies = [
    "tomlkit>=0.13.2",
    "result>=0.17.0",
    "jsonschema>=4.23.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.coverage.run]
source = [ "mktech" ]

[tool.mypy]
packages = [ "mktech", "test" ]
strict = true

[tool.pytest.ini_options]
testpaths = [ "test" ]

[tool.pdm]
distribution = true

[dependency-groups]
test = [
    "coverage>=7.6.4",
    "flake8>=7.1.1",
    "mypy>=1.13.0",
    "pytest>=8.3.3",
    "nox>=2024.10.9",
]
dev = [
    "python-lsp-server[all]>=1.12.0",
    "ipdb>=0.13.13",
    "pdoc3>=0.11.1",
    "pylsp-mypy>=0.6.9",
    "types-jsonschema>=4.23.0.20240813",
]
